# Generated by Django 2.2.6 on 2019-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='default_avatar.png', null=True, upload_to='utilisateur/'),
        ),
    ]
