# Generated by Django 2.2.6 on 2019-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='specialite',
            field=models.ManyToManyField(related_name='user_specialite', to='Utilisateurs.Specialite'),
        ),
    ]
