# Generated by Django 2.2.6 on 2019-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_auto_20191029_1412'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique email'),
        ),
    ]
