# Generated by Django 2.2.6 on 2019-10-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='specialite',
        ),
        migrations.AddField(
            model_name='myuser',
            name='specialite',
            field=models.ManyToManyField(related_name='user_specialite', to='Utilisateurs.Specialite'),
        ),
    ]
