# Generated by Django 2.2.6 on 2019-11-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0003_auto_20191029_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='/utilisateur/user2.png', upload_to='utilisateur/'),
        ),
    ]
