# Generated by Django 2.2.6 on 2019-10-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allConfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmap',
            old_name='laltitude',
            new_name='latitude',
        ),
    ]
