# Generated by Django 2.2.6 on 2019-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allConfig', '0002_auto_20191026_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerfront',
            name='about_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerfront',
            name='folow_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footerfront',
            name='newslater_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='headerfront',
            name='about_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headerfront',
            name='blog_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headerfront',
            name='cat_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headerfront',
            name='contct_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headerfront',
            name='index_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
