# Generated by Django 2.2.6 on 2019-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allConfig', '0003_auto_20191026_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='workingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('openHours', models.TimeField()),
                ('closeHours', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='allinfo',
            name='commune',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='allinfo',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allinfo',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
