# Generated by Django 2.2.6 on 2019-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allConfig', '0005_auto_20191026_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinfo',
            name='contactText',
            field=models.TextField(null=True),
        ),
    ]
