# Generated by Django 2.2.6 on 2019-10-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_myuser'),
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article_auteur', to='Utilisateurs.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='Utilisateurs.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='Utilisateurs.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsecommentaire',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_response_comment', to='Utilisateurs.MyUser'),
            preserve_default=False,
        ),
    ]
