# Generated by Django 2.2.6 on 2019-10-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20191025_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='nom',
        ),
    ]
