# Generated by Django 2.2.6 on 2019-10-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20191028_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
